### ISSUE TITLE
Can't import Loader

### ISSUE THREAD

**Issue by dpalbrecht** [NVIDIA-Merlin/dataloader#60]
The following commands produce the below error on import as of this morning, compared to about 12 hours ago:
```
!pip install merlin-dataloader
from merlin.loader.torch import Loader 
```

```
ImportError                               Traceback (most recent call last)
/tmp/ipykernel_27/1850034830.py in <module>
     14 get_ipython().system('pip install merlin-dataloader')
---> 15 from merlin.loader.torch import Loader
     16 from merlin.io import Dataset
     17 

/opt/conda/lib/python3.7/site-packages/merlin/loader/torch.py in <module>
     19 
     20 from merlin.core.dispatch import HAS_GPU
---> 21 from merlin.loader.loader_base import LoaderBase
     22 
     23 numpy_to_torch_dtype_dict = {

/opt/conda/lib/python3.7/site-packages/merlin/loader/loader_base.py in <module>
     38     pull_apart_list,
     39 )
---> 40 from merlin.dag import BaseOperator, ColumnSelector, DictArray, Graph, Node
     41 from merlin.dag.executors import LocalExecutor
     42 from merlin.io import shuffle_df

ImportError: cannot import name 'DictArray' from 'merlin.dag' (/opt/conda/lib/python3.7/site-packages/merlin/dag/__init__.py)
```

**Comment by oliverholworthy** [comment]
Based on the error, it looks like you're running with Python 3.7. The lastest version of Merlin Packages all have a min python version of 3.8. However, we missed specifying this in our dataloader package. Will update this, but you'll stil get the error in Python 3.7 though.

If you run this in Python 3.8 or higher environment, it should import without an error.

**Comment by dpalbrecht** [comment]
@oliverholworthy thanks very much! What's odd to me is these same commands worked last night (about 12 hours before this error popped up this morning). I'm running them in Kaggle notebooks, in which environments don't change I think, following an example from Radek. Does that change the root cause of this issue?

**Comment by radekosmulski** [comment]
Hey @dpalbrecht! 🙂 I believe it was because previously an older version of `merlin-dataloader` was getting installed which worked with Python 3.7.  Could you please try the new version of the notebook where I pin the version of `merlin-dataloader` to `0.0.2`?

Nice to see you here and thank you for raising the issue 🙂

**Comment by dpalbrecht** [comment]
Thanks for the help @radekosmulski 😄 that fixed the issue! Now I can go back to looping through the data incredibly quickly. I appreciate you sharing such a useful tool for the competition (as well as work)!
